[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build_tracy]
command = "cargo"
args = ["build", "--features", "tracy"]

[tasks.clean_run]   
workspace = false
command = "./target/debug/test_game"
dependencies = ["clean", "build"]

[tasks.run]
workspace = false
command = "./target/debug/test_game"
dependencies = ["build"]

[tasks.run_tracy]
workspace = false
command = "./target/debug/test_game"
dependencies = ["build_tracy"]