[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.clean_run]
command = "./target/debug/potato-engine"
dependencies = ["clean", "build"]

[tasks.run]
command = "./target/debug/potato-engine"
dependencies = ["build"]